name: GSC Click Drop Alert

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC (7:30 AM IST)
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GSC Click Drop Script
        env:
          GSC_CREDENTIALS: ${{ secrets.GSC_CREDENTIALS }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        run: python gsc_click_drop_alert.py
